In [4]:
import numpy as np
A = np.array(
    [
        [0, 1],
        [2, 3],
        [4, 5]
    ]
)
A

array([[0, 1],
       [2, 3],
       [4, 5]])

In [5]:
B = np.array(
    [
        [0, 1, 2, 3],
        [4, 5, 6, 7]
    ]
)
B

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [7]:
np.dot(A, B)

array([[ 4,  5,  6,  7],
       [12, 17, 22, 27],
       [20, 29, 38, 47]])

In [9]:
C = np.array(
    [
        [ 4,  5,  6,  7],
       [12, 17, 22, 27],
       [20, 29, 38, 47]
    ]
    )
max_C = C.max()
max_C

47